### ISSUE TITLE
Spatny vzorec na spocitani polomeru diry

### ISSUE THREAD

**Issue by kucerp21** [3DprintFIT/B181CW-Assignment#1]
Mam pocit, ze vzorec na spocitani polomeru diry by mel byt `holer - (ratio/2)*j` namisto uvedeneho `holer - ratio*j`.

**Comment by kucerp21** [comment]
V zadani je vlastne zapsano veliksot diry, v tom pripade by ale mel byt vzorec stejne jiny, a to `2*holer - ratio*j`

**Comment by kucerp21** [comment]
Také mi přijde, že je nedostatečně definované rozložení děr:

> Díry jsou rovnoměrně rozložené podle počtu po celé špičce od hrany hlavní koule do středu "druhé koule" (s polomerem r2).

**Comment by kucerp21** [comment]
Také mi přijde, že není dostatečně definované rozložení děr po špičce

> Díry jsou rovnoměrně rozložené podle počtu po celé špičce od hrany hlavní koule do středu "druhé koule" (s polomerem r2).

Toto mi neřekne jestli mám díry rovnoměrně rozložit, tak že je vždy stejná mezera mezi jejich hranami, či středy. Také mi to neříká, jestli první díra má být co nejníže, nebo jestli má být mezera mezi první dírou a hlavní koulí podle rozložení všech děr. 
Na 3d modelu to totiž vypadá tak, že první díra je co nejblíže k hlavní kouli a dále jsou všechny ostatní díry rovnoměrně rozloženy na zbytku. Naopak poslední díra se vršku cylindru špičky nikdy nedotýká a má nad sebou jasně mezeru. Na popisujícím 2d modelu je ale vrchní díra umístěna bez jakékoliv mezery tak, aby se vršku dotýkala.

Chápu, že je toto alfa verze, pouze pdootýkám, že pokud to nebyo v plánu, tak by se toto mělo upřesnit.

EDIT: Issue byl uzavřen omylem

**Comment by Hanyman8** [comment]
Ahoj Kůčo,
díky za poznatky. Dnes večer to zkusím lépe dodefinovat.
